### ISSUE TITLE
gcr.io/cos-cloud/cos-gpu-installer v2.0.3  (--no-kernel-module)

### ISSUE THREAD

**Issue by dickmao** [GoogleCloudPlatform/cos-gpu-installer#66]
The cos-gpu-installer in that docker image contains the same strings as cos-gpu-installer-docker/entrypoint.sh and yet is a golang binary?  Is that source available somewhere?

In particular, I'm wondering what governs whether the `--no-kernel-module` option gets tacked onto the `/tmp/extract/nvidia-installer` invocation.

**Comment by rkolchmeyer** [comment]
The source for that version is available here: https://cos.googlesource.com/cos/tools/+/refs/heads/master/src/cmd/cos_gpu_installer/

**Comment by dickmao** [comment]
You're the man.  Thanks.

**Comment by dickmao** [comment]
Gosh, while I have your attention, is there a way to track up the provenance of the various cos releases, e.g., suppose I wanted to `repo init -b` to the cos-85-13310-1209-3 release.  Right now, the only branches I know about are https://cos.googlesource.com/cos/manifest.git .  I work off release-R85-13310.B, but I've no way of knowing how close or far that is to the aforementioned cos-85-13310-1209-3.

**Comment by rkolchmeyer** [comment]
You should be able to `repo init -b` to a tag in the manifest-snapshots repository: https://cos.googlesource.com/cos/manifest-snapshots

That should do what you want, if I'm reading your comment correctly.

**Comment by dickmao** [comment]
You, sir, are blowing my mind with wisdom.  Many, many thanks.

**Comment by dickmao** [comment]
Is there a mailing list, github issues, or forum where these cos-related questions are more appropriate?  Thanks in advance.

**Comment by rkolchmeyer** [comment]
There are the places listed here (https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us), although I don't think those places are particularly active when it comes to COS-related questions.
